[package]
name = "threshold_crypto_ffi"
version = "0.1.0"

[dependencies]
libc = "0.2.43"
threshold_crypto = { version = "0.2.1", git = "https://github.com/poanetwork/threshold_crypto" }

[lib]
crate-type = ["dylib"]
